spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/coupon_project
    username: root
    password: s9htqkes
    driverClassName: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

